export interface AwsPolicy {
    Version: string;
    Statement: AwsPolicyStatement[];
}

export interface AwsPolicyStatement {
    Sid?: string;
    Effect: 'Allow' | 'Deny';
    Action?: string | string[];
    NotAction?: string | string[];
    Resource?: string | string[];
    NotResource?: string | string[];

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Condition?: Record<any, any>;
}

// Generated by ../scripts/gather_aws_service_info.py
export const awsServices = [
    {
        name: 'AWS App2Container',
        namespace: 'a2c',
    },
    {
        name: 'Alexa for Business',
        namespace: 'a4b',
    },
    {
        name: 'AWS IAM Access Analyzer',
        namespace: 'access-analyzer',
    },
    {
        name: 'AWS Account Management',
        namespace: 'account',
    },
    {
        name: 'AWS Certificate Manager',
        namespace: 'acm',
    },
    {
        name: 'AWS Private Certificate Authority',
        namespace: 'acm-pca',
    },
    {
        name: 'AWS Activate',
        namespace: 'activate',
    },
    {
        name: 'Amazon AI Operations',
        namespace: 'aiops',
    },
    {
        name: 'Amazon Managed Workflows for Apache Airflow',
        namespace: 'airflow',
    },
    {
        name: 'AWS Amplify',
        namespace: 'amplify',
    },
    {
        name: 'AWS Amplify Admin',
        namespace: 'amplifybackend',
    },
    {
        name: 'AWS Amplify UI Builder',
        namespace: 'amplifyuibuilder',
    },
    {
        name: 'Amazon OpenSearch Serverless',
        namespace: 'aoss',
    },
    {
        name: 'Manage - Amazon API Gateway',
        namespace: 'apigateway',
    },
    {
        name: 'Amazon AppIntegrations',
        namespace: 'app-integrations',
    },
    {
        name: 'AWS AppConfig',
        namespace: 'appconfig',
    },
    {
        name: 'AWS AppFabric',
        namespace: 'appfabric',
    },
    {
        name: 'Amazon AppFlow',
        namespace: 'appflow',
    },
    {
        name: 'AWS Application Auto Scaling',
        namespace: 'application-autoscaling',
    },
    {
        name: 'AWS Application Cost Profiler Service',
        namespace: 'application-cost-profiler',
    },
    {
        name: 'Amazon CloudWatch Application Signals',
        namespace: 'application-signals',
    },
    {
        name: 'AWS Application Transformation Service',
        namespace: 'application-transformation',
    },
    {
        name: 'Amazon CloudWatch Application Insights',
        namespace: 'applicationinsights',
    },
    {
        name: 'AWS App Mesh',
        namespace: 'appmesh',
    },
    {
        name: 'AWS App Mesh Preview',
        namespace: 'appmesh-preview',
    },
    {
        name: 'AWS App Runner',
        namespace: 'apprunner',
    },
    {
        name: 'Amazon AppStream 2.0',
        namespace: 'appstream',
    },
    {
        name: 'AWS App Studio',
        namespace: 'appstudio',
    },
    {
        name: 'AWS AppSync',
        namespace: 'appsync',
    },
    {
        name: 'AWS Mainframe Modernization Application Testing',
        namespace: 'apptest',
    },
    {
        name: 'Amazon Managed Service for Prometheus',
        namespace: 'aps',
    },
    {
        name: 'Amazon Application Recovery Controller - Zonal Shift',
        namespace: 'arc-zonal-shift',
    },
    {
        name: 'Application Discovery Arsenal',
        namespace: 'arsenal',
    },
    {
        name: 'AWS Artifact',
        namespace: 'artifact',
    },
    {
        name: 'Amazon Athena',
        namespace: 'athena',
    },
    {
        name: 'AWS Audit Manager',
        namespace: 'auditmanager',
    },
    {
        name: 'Amazon EC2 Auto Scaling',
        namespace: 'autoscaling',
    },
    {
        name: 'AWS Auto Scaling',
        namespace: 'autoscaling-plans',
    },
    {
        name: 'AWS Marketplace',
        namespace: 'aws-marketplace',
    },
    {
        name: 'AWS Marketplace Management Portal',
        namespace: 'aws-marketplace-management',
    },
    {
        name: 'AWS Billing Console',
        namespace: 'aws-portal',
    },
    {
        name: 'AWS Connector Service',
        namespace: 'awsconnector',
    },
    {
        name: 'AWS B2B Data Interchange',
        namespace: 'b2bi',
    },
    {
        name: 'AWS Backup',
        namespace: 'backup',
    },
    {
        name: 'AWS Backup Gateway',
        namespace: 'backup-gateway',
    },
    {
        name: 'AWS Backup Search',
        namespace: 'backup-search',
    },
    {
        name: 'AWS Backup storage',
        namespace: 'backup-storage',
    },
    {
        name: 'AWS Batch',
        namespace: 'batch',
    },
    {
        name: 'AWS Billing And Cost Management Data Exports',
        namespace: 'bcm-data-exports',
    },
    {
        name: 'AWS Billing And Cost Management Pricing Calculator',
        namespace: 'bcm-pricing-calculator',
    },
    {
        name: 'Amazon Bedrock',
        namespace: 'bedrock',
    },
    {
        name: 'AWS Billing',
        namespace: 'billing',
    },
    {
        name: 'AWS Billing Conductor',
        namespace: 'billingconductor',
    },
    {
        name: 'Amazon Braket',
        namespace: 'braket',
    },
    {
        name: 'AWS Budget Service',
        namespace: 'budgets',
    },
    {
        name: 'AWS BugBust',
        namespace: 'bugbust',
    },
    {
        name: 'Amazon Connect Cases',
        namespace: 'cases',
    },
    {
        name: 'Amazon Keyspaces (for Apache Cassandra)',
        namespace: 'cassandra',
    },
    {
        name: 'AWS Cost Explorer Service',
        namespace: 'ce',
    },
    {
        name: 'AWS Chatbot',
        namespace: 'chatbot',
    },
    {
        name: 'Amazon Chime',
        namespace: 'chime',
    },
    {
        name: 'AWS Clean Rooms',
        namespace: 'cleanrooms',
    },
    {
        name: 'AWS Clean Rooms ML',
        namespace: 'cleanrooms-ml',
    },
    {
        name: 'AWS Cloud9',
        namespace: 'cloud9',
    },
    {
        name: 'Amazon Cloud Directory',
        namespace: 'clouddirectory',
    },
    {
        name: 'AWS CloudFormation',
        namespace: 'cloudformation',
    },
    {
        name: 'Amazon CloudFront',
        namespace: 'cloudfront',
    },
    {
        name: 'Amazon CloudFront KeyValueStore',
        namespace: 'cloudfront-keyvaluestore',
    },
    {
        name: 'AWS CloudHSM',
        namespace: 'cloudhsm',
    },
    {
        name: 'Amazon CloudSearch',
        namespace: 'cloudsearch',
    },
    {
        name: 'AWS CloudShell',
        namespace: 'cloudshell',
    },
    {
        name: 'AWS CloudTrail',
        namespace: 'cloudtrail',
    },
    {
        name: 'AWS CloudTrail Data',
        namespace: 'cloudtrail-data',
    },
    {
        name: 'Amazon CloudWatch',
        namespace: 'cloudwatch',
    },
    {
        name: 'AWS CodeArtifact',
        namespace: 'codeartifact',
    },
    {
        name: 'AWS CodeBuild',
        namespace: 'codebuild',
    },
    {
        name: 'Amazon CodeCatalyst',
        namespace: 'codecatalyst',
    },
    {
        name: 'AWS CodeCommit',
        namespace: 'codecommit',
    },
    {
        name: 'AWS CodeConnections',
        namespace: 'codeconnections',
    },
    {
        name: 'AWS CodeDeploy',
        namespace: 'codedeploy',
    },
    {
        name: 'AWS CodeDeploy secure host commands service',
        namespace: 'codedeploy-commands-secure',
    },
    {
        name: 'Amazon CodeGuru',
        namespace: 'codeguru',
    },
    {
        name: 'Amazon CodeGuru Profiler',
        namespace: 'codeguru-profiler',
    },
    {
        name: 'Amazon CodeGuru Reviewer',
        namespace: 'codeguru-reviewer',
    },
    {
        name: 'Amazon CodeGuru Security',
        namespace: 'codeguru-security',
    },
    {
        name: 'AWS CodePipeline',
        namespace: 'codepipeline',
    },
    {
        name: 'AWS CodeStar',
        namespace: 'codestar',
    },
    {
        name: 'AWS CodeStar Connections',
        namespace: 'codestar-connections',
    },
    {
        name: 'AWS CodeStar Notifications',
        namespace: 'codestar-notifications',
    },
    {
        name: 'Amazon CodeWhisperer',
        namespace: 'codewhisperer',
    },
    {
        name: 'Amazon Cognito Identity',
        namespace: 'cognito-identity',
    },
    {
        name: 'Amazon Cognito User Pools',
        namespace: 'cognito-idp',
    },
    {
        name: 'Amazon Cognito Sync',
        namespace: 'cognito-sync',
    },
    {
        name: 'Amazon Comprehend',
        namespace: 'comprehend',
    },
    {
        name: 'Amazon Comprehend Medical',
        namespace: 'comprehendmedical',
    },
    {
        name: 'AWS Compute Optimizer',
        namespace: 'compute-optimizer',
    },
    {
        name: 'AWS Config',
        namespace: 'config',
    },
    {
        name: 'Amazon Connect',
        namespace: 'connect',
    },
    {
        name: 'Amazon Connect Outbound Campaigns',
        namespace: 'connect-campaigns',
    },
    {
        name: 'AWS Console Mobile App',
        namespace: 'consoleapp',
    },
    {
        name: 'AWS Consolidated Billing',
        namespace: 'consolidatedbilling',
    },
    {
        name: 'AWS Control Catalog',
        namespace: 'controlcatalog',
    },
    {
        name: 'AWS Control Tower',
        namespace: 'controltower',
    },
    {
        name: 'AWS Cost Optimization Hub',
        namespace: 'cost-optimization-hub',
    },
    {
        name: 'AWS Cost and Usage Report',
        namespace: 'cur',
    },
    {
        name: 'AWS Customer Verification Service',
        namespace: 'customer-verification',
    },
    {
        name: 'AWS Glue DataBrew',
        namespace: 'databrew',
    },
    {
        name: 'AWS Data Exchange',
        namespace: 'dataexchange',
    },
    {
        name: 'AWS Data Pipeline',
        namespace: 'datapipeline',
    },
    {
        name: 'AWS DataSync',
        namespace: 'datasync',
    },
    {
        name: 'Amazon DataZone',
        namespace: 'datazone',
    },
    {
        name: 'Amazon DynamoDB Accelerator (DAX)',
        namespace: 'dax',
    },
    {
        name: 'Database Query Metadata Service',
        namespace: 'dbqms',
    },
    {
        name: 'AWS Deadline Cloud',
        namespace: 'deadline',
    },
    {
        name: 'AWS DeepComposer',
        namespace: 'deepcomposer',
    },
    {
        name: 'AWS DeepRacer',
        namespace: 'deepracer',
    },
    {
        name: 'Amazon Detective',
        namespace: 'detective',
    },
    {
        name: 'AWS Device Farm',
        namespace: 'devicefarm',
    },
    {
        name: 'Amazon DevOps Guru',
        namespace: 'devops-guru',
    },
    {
        name: 'AWS Direct Connect',
        namespace: 'directconnect',
    },
    {
        name: 'AWS Application Discovery Service',
        namespace: 'discovery',
    },
    {
        name: 'Amazon Data Lifecycle Manager',
        namespace: 'dlm',
    },
    {
        name: 'AWS Database Migration Service',
        namespace: 'dms',
    },
    {
        name: 'Amazon DocumentDB Elastic Clusters',
        namespace: 'docdb-elastic',
    },
    {
        name: 'AWS Elastic Disaster Recovery',
        namespace: 'drs',
    },
    {
        name: 'AWS Directory Service',
        namespace: 'ds',
    },
    {
        name: 'AWS Directory Service Data',
        namespace: 'ds-data',
    },
    {
        name: 'Amazon Aurora DSQL',
        namespace: 'dsql',
    },
    {
        name: 'Amazon DynamoDB',
        namespace: 'dynamodb',
    },
    {
        name: 'Amazon Elastic Block Store',
        namespace: 'ebs',
    },
    {
        name: 'Amazon EC2',
        namespace: 'ec2',
    },
    {
        name: 'Amazon EC2 Instance Connect',
        namespace: 'ec2-instance-connect',
    },
    {
        name: 'Amazon Message Delivery Service',
        namespace: 'ec2messages',
    },
    {
        name: 'Amazon Elastic Container Registry',
        namespace: 'ecr',
    },
    {
        name: 'Amazon Elastic Container Registry Public',
        namespace: 'ecr-public',
    },
    {
        name: 'Amazon Elastic Container Service',
        namespace: 'ecs',
    },
    {
        name: 'Amazon Elastic Kubernetes Service',
        namespace: 'eks',
    },
    {
        name: 'Amazon EKS Auth',
        namespace: 'eks-auth',
    },
    {
        name: 'Amazon ElastiCache',
        namespace: 'elasticache',
    },
    {
        name: 'AWS Elastic Beanstalk',
        namespace: 'elasticbeanstalk',
    },
    {
        name: 'Amazon Elastic File System',
        namespace: 'elasticfilesystem',
    },
    {
        name: 'Elastic Load Balancing',
        namespace: 'elasticloadbalancing',
    },
    {
        name: 'Amazon Elastic MapReduce',
        namespace: 'elasticmapreduce',
    },
    {
        name: 'Amazon Elastic Transcoder',
        namespace: 'elastictranscoder',
    },
    {
        name: 'AWS Elemental Appliances and Software Activation Service',
        namespace: 'elemental-activations',
    },
    {
        name: 'AWS Elemental Appliances and Software',
        namespace: 'elemental-appliances-software',
    },
    {
        name: 'AWS Elemental Support Cases',
        namespace: 'elemental-support-cases',
    },
    {
        name: 'AWS Elemental Support Content',
        namespace: 'elemental-support-content',
    },
    {
        name: 'Amazon EMR on EKS (EMR Containers)',
        namespace: 'emr-containers',
    },
    {
        name: 'Amazon EMR Serverless',
        namespace: 'emr-serverless',
    },
    {
        name: 'AWS Entity Resolution',
        namespace: 'entityresolution',
    },
    {
        name: 'Amazon OpenSearch Service',
        namespace: 'es',
    },
    {
        name: 'Amazon EventBridge',
        namespace: 'events',
    },
    {
        name: 'Amazon CloudWatch Evidently',
        namespace: 'evidently',
    },
    {
        name: 'Amazon API Gateway',
        namespace: 'execute-api',
    },
    {
        name: 'Amazon FinSpace',
        namespace: 'finspace',
    },
    {
        name: 'Amazon FinSpace API',
        namespace: 'finspace-api',
    },
    {
        name: 'Amazon Kinesis Firehose',
        namespace: 'firehose',
    },
    {
        name: 'AWS Fault Injection Service',
        namespace: 'fis',
    },
    {
        name: 'AWS Firewall Manager',
        namespace: 'fms',
    },
    {
        name: 'Amazon Forecast',
        namespace: 'forecast',
    },
    {
        name: 'Amazon Fraud Detector',
        namespace: 'frauddetector',
    },
    {
        name: 'Amazon FreeRTOS',
        namespace: 'freertos',
    },
    {
        name: 'AWS Free Tier',
        namespace: 'freetier',
    },
    {
        name: 'Amazon FSx',
        namespace: 'fsx',
    },
    {
        name: 'Amazon GameLift',
        namespace: 'gamelift',
    },
    {
        name: 'Amazon GameLift Streams',
        namespace: 'gameliftstreams',
    },
    {
        name: 'Amazon Location',
        namespace: 'geo',
    },
    {
        name: 'Amazon Location Service Maps',
        namespace: 'geo-maps',
    },
    {
        name: 'Amazon Location Service Places',
        namespace: 'geo-places',
    },
    {
        name: 'Amazon Location Service Routes',
        namespace: 'geo-routes',
    },
    {
        name: 'Amazon S3 Glacier',
        namespace: 'glacier',
    },
    {
        name: 'AWS Global Accelerator',
        namespace: 'globalaccelerator',
    },
    {
        name: 'AWS Glue',
        namespace: 'glue',
    },
    {
        name: 'Amazon Managed Grafana',
        namespace: 'grafana',
    },
    {
        name: 'AWS IoT Greengrass',
        namespace: 'greengrass',
    },
    {
        name: 'AWS Ground Station',
        namespace: 'groundstation',
    },
    {
        name: 'Amazon GroundTruth Labeling',
        namespace: 'groundtruthlabeling',
    },
    {
        name: 'Amazon GuardDuty',
        namespace: 'guardduty',
    },
    {
        name: 'AWS Health APIs and Notifications',
        namespace: 'health',
    },
    {
        name: 'AWS HealthLake',
        namespace: 'healthlake',
    },
    {
        name: 'Amazon Honeycode',
        namespace: 'honeycode',
    },
    {
        name: 'AWS Identity and Access Management',
        namespace: 'iam',
    },
    {
        name: 'AWS Identity Sync',
        namespace: 'identity-sync',
    },
    {
        name: 'AWS Identity Store',
        namespace: 'identitystore',
    },
    {
        name: 'AWS Identity Store Auth',
        namespace: 'identitystore-auth',
    },
    {
        name: 'Amazon EC2 Image Builder',
        namespace: 'imagebuilder',
    },
    {
        name: 'AWS Import Export',
        namespace: 'importexport',
    },
    {
        name: 'Amazon Inspector',
        namespace: 'inspector',
    },
    {
        name: 'Amazon InspectorScan',
        namespace: 'inspector-scan',
    },
    {
        name: 'Amazon Inspector2',
        namespace: 'inspector2',
    },
    {
        name: 'Amazon CloudWatch Internet Monitor',
        namespace: 'internetmonitor',
    },
    {
        name: 'AWS Invoicing Service',
        namespace: 'invoicing',
    },
    {
        name: 'AWS IoT',
        namespace: 'iot',
    },
    {
        name: 'AWS IoT Device Tester',
        namespace: 'iot-device-tester',
    },
    {
        name: 'AWS IoT 1-Click',
        namespace: 'iot1click',
    },
    {
        name: 'AWS IoT Analytics',
        namespace: 'iotanalytics',
    },
    {
        name: 'AWS IoT Core Device Advisor',
        namespace: 'iotdeviceadvisor',
    },
    {
        name: 'AWS IoT Events',
        namespace: 'iotevents',
    },
    {
        name: 'AWS IoT Fleet Hub for Device Management',
        namespace: 'iotfleethub',
    },
    {
        name: 'AWS IoT FleetWise',
        namespace: 'iotfleetwise',
    },
    {
        name: 'AWS IoT Jobs DataPlane',
        namespace: 'iotjobsdata',
    },
    {
        name: 'AWS IoT managed integrations feature of IoT Device Management',
        namespace: 'iotmanagedintegrations',
    },
    {
        name: 'AWS IoT SiteWise',
        namespace: 'iotsitewise',
    },
    {
        name: 'AWS IoT TwinMaker',
        namespace: 'iottwinmaker',
    },
    {
        name: 'AWS IoT Wireless',
        namespace: 'iotwireless',
    },
    {
        name: 'AWS IQ',
        namespace: 'iq',
    },
    {
        name: 'AWS IQ Permissions',
        namespace: 'iq-permission',
    },
    {
        name: 'Amazon Interactive Video Service',
        namespace: 'ivs',
    },
    {
        name: 'Amazon Interactive Video Service Chat',
        namespace: 'ivschat',
    },
    {
        name: 'Amazon Managed Streaming for Apache Kafka',
        namespace: 'kafka',
    },
    {
        name: 'Apache Kafka APIs for Amazon MSK clusters',
        namespace: 'kafka-cluster',
    },
    {
        name: 'Amazon Managed Streaming for Kafka Connect',
        namespace: 'kafkaconnect',
    },
    {
        name: 'Amazon Kendra',
        namespace: 'kendra',
    },
    {
        name: 'Amazon Kendra Intelligent Ranking',
        namespace: 'kendra-ranking',
    },
    {
        name: 'Amazon Kinesis Data Streams',
        namespace: 'kinesis',
    },
    {
        name: 'Amazon Kinesis Analytics',
        namespace: 'kinesisanalytics',
    },
    {
        name: 'Amazon Kinesis Video Streams',
        namespace: 'kinesisvideo',
    },
    {
        name: 'AWS Key Management Service',
        namespace: 'kms',
    },
    {
        name: 'AWS Lake Formation',
        namespace: 'lakeformation',
    },
    {
        name: 'AWS Lambda',
        namespace: 'lambda',
    },
    {
        name: 'AWS Launch Wizard',
        namespace: 'launchwizard',
    },
    {
        name: 'Amazon Lex',
        namespace: 'lex',
    },
    {
        name: 'AWS License Manager',
        namespace: 'license-manager',
    },
    {
        name: 'AWS License Manager Linux Subscriptions Manager',
        namespace: 'license-manager-linux-subscriptions',
    },
    {
        name: 'AWS License Manager User Subscriptions',
        namespace: 'license-manager-user-subscriptions',
    },
    {
        name: 'Amazon Lightsail',
        namespace: 'lightsail',
    },
    {
        name: 'Amazon CloudWatch Logs',
        namespace: 'logs',
    },
    {
        name: 'Amazon Lookout for Equipment',
        namespace: 'lookoutequipment',
    },
    {
        name: 'Amazon Lookout for Metrics',
        namespace: 'lookoutmetrics',
    },
    {
        name: 'Amazon Lookout for Vision',
        namespace: 'lookoutvision',
    },
    {
        name: 'AWS Mainframe Modernization Service',
        namespace: 'm2',
    },
    {
        name: 'Amazon Machine Learning',
        namespace: 'machinelearning',
    },
    {
        name: 'Amazon Macie',
        namespace: 'macie2',
    },
    {
        name: 'Amazon Managed Blockchain',
        namespace: 'managedblockchain',
    },
    {
        name: 'Amazon Managed Blockchain Query',
        namespace: 'managedblockchain-query',
    },
    {
        name: 'AWS Migration Acceleration Program Credits',
        namespace: 'mapcredits',
    },
    {
        name: 'AWS Marketplace Commerce Analytics Service',
        namespace: 'marketplacecommerceanalytics',
    },
    {
        name: 'Amazon Mechanical Turk',
        namespace: 'mechanicalturk',
    },
    {
        name: 'AWS Elemental MediaConnect',
        namespace: 'mediaconnect',
    },
    {
        name: 'AWS Elemental MediaConvert',
        namespace: 'mediaconvert',
    },
    {
        name: 'AmazonMediaImport',
        namespace: 'mediaimport',
    },
    {
        name: 'AWS Elemental MediaLive',
        namespace: 'medialive',
    },
    {
        name: 'AWS Elemental MediaPackage',
        namespace: 'mediapackage',
    },
    {
        name: 'AWS Elemental MediaPackage VOD',
        namespace: 'mediapackage-vod',
    },
    {
        name: 'AWS Elemental MediaPackage V2',
        namespace: 'mediapackagev2',
    },
    {
        name: 'AWS Elemental MediaStore',
        namespace: 'mediastore',
    },
    {
        name: 'AWS Elemental MediaTailor',
        namespace: 'mediatailor',
    },
    {
        name: 'AWS HealthImaging',
        namespace: 'medical-imaging',
    },
    {
        name: 'Amazon MemoryDB',
        namespace: 'memorydb',
    },
    {
        name: 'AWS Migration Hub',
        namespace: 'mgh',
    },
    {
        name: 'AWS Application Migration Service',
        namespace: 'mgn',
    },
    {
        name: 'AWS Migration Hub Orchestrator',
        namespace: 'migrationhub-orchestrator',
    },
    {
        name: 'AWS Migration Hub Strategy Recommendations',
        namespace: 'migrationhub-strategy',
    },
    {
        name: 'Amazon Mobile Analytics',
        namespace: 'mobileanalytics',
    },
    {
        name: 'Amazon Pinpoint',
        namespace: 'mobiletargeting',
    },
    {
        name: 'Amazon Monitron',
        namespace: 'monitron',
    },
    {
        name: 'Amazon MQ',
        namespace: 'mq',
    },
    {
        name: 'Amazon Neptune',
        namespace: 'neptune-db',
    },
    {
        name: 'Amazon Neptune Analytics',
        namespace: 'neptune-graph',
    },
    {
        name: 'AWS Network Firewall',
        namespace: 'network-firewall',
    },
    {
        name: 'Network Flow Monitor',
        namespace: 'networkflowmonitor',
    },
    {
        name: 'AWS Network Manager',
        namespace: 'networkmanager',
    },
    {
        name: 'AWS Network Manager Chat',
        namespace: 'networkmanager-chat',
    },
    {
        name: 'Amazon CloudWatch Network Monitor',
        namespace: 'networkmonitor',
    },
    {
        name: 'Amazon Nimble Studio',
        namespace: 'nimble',
    },
    {
        name: 'AWS User Notifications',
        namespace: 'notifications',
    },
    {
        name: 'AWS User Notifications Contacts',
        namespace: 'notifications-contacts',
    },
    {
        name: 'Amazon CloudWatch Observability Access Manager',
        namespace: 'oam',
    },
    {
        name: 'Amazon CloudWatch Observability Admin Service',
        namespace: 'observabilityadmin',
    },
    {
        name: 'AWS HealthOmics',
        namespace: 'omics',
    },
    {
        name: 'Amazon One Enterprise',
        namespace: 'one',
    },
    {
        name: 'Amazon OpenSearch',
        namespace: 'opensearch',
    },
    {
        name: 'AWS OpsWorks',
        namespace: 'opsworks',
    },
    {
        name: 'AWS OpsWorks Configuration Management',
        namespace: 'opsworks-cm',
    },
    {
        name: 'AWS Organizations',
        namespace: 'organizations',
    },
    {
        name: 'Amazon OpenSearch Ingestion',
        namespace: 'osis',
    },
    {
        name: 'AWS Outposts',
        namespace: 'outposts',
    },
    {
        name: 'AWS Panorama',
        namespace: 'panorama',
    },
    {
        name: 'AWS Partner Central Selling',
        namespace: 'partnercentral',
    },
    {
        name: 'AWS Partner central account management',
        namespace: 'partnercentral-account-management',
    },
    {
        name: 'AWS Payment Cryptography',
        namespace: 'payment-cryptography',
    },
    {
        name: 'AWS Payments',
        namespace: 'payments',
    },
    {
        name: 'AWS Private CA Connector for Active Directory',
        namespace: 'pca-connector-ad',
    },
    {
        name: 'AWS Private CA Connector for SCEP',
        namespace: 'pca-connector-scep',
    },
    {
        name: 'AWS Parallel Computing Service',
        namespace: 'pcs',
    },
    {
        name: 'Amazon Personalize',
        namespace: 'personalize',
    },
    {
        name: 'AWS Performance Insights',
        namespace: 'pi',
    },
    {
        name: 'Amazon EventBridge Pipes',
        namespace: 'pipes',
    },
    {
        name: 'Amazon Polly',
        namespace: 'polly',
    },
    {
        name: 'AWS Price List',
        namespace: 'pricing',
    },
    {
        name: 'AWS service providing managed private networks',
        namespace: 'private-networks',
    },
    {
        name: 'Amazon Connect Customer Profiles',
        namespace: 'profile',
    },
    {
        name: 'AWS Proton',
        namespace: 'proton',
    },
    {
        name: 'AWS Purchase Orders Console',
        namespace: 'purchase-orders',
    },
    {
        name: 'Amazon Q',
        namespace: 'q',
    },
    {
        name: 'Amazon Q Business Q Apps',
        namespace: 'qapps',
    },
    {
        name: 'Amazon Q Business',
        namespace: 'qbusiness',
    },
    {
        name: 'Amazon Q Developer',
        namespace: 'qdeveloper',
    },
    {
        name: 'Amazon QLDB',
        namespace: 'qldb',
    },
    {
        name: 'Amazon QuickSight',
        namespace: 'quicksight',
    },
    {
        name: 'AWS Resource Access Manager (RAM)',
        namespace: 'ram',
    },
    {
        name: 'AWS Recycle Bin',
        namespace: 'rbin',
    },
    {
        name: 'Amazon RDS',
        namespace: 'rds',
    },
    {
        name: 'Amazon RDS Data API',
        namespace: 'rds-data',
    },
    {
        name: 'Amazon RDS IAM Authentication',
        namespace: 'rds-db',
    },
    {
        name: 'Amazon Redshift',
        namespace: 'redshift',
    },
    {
        name: 'Amazon Redshift Data API',
        namespace: 'redshift-data',
    },
    {
        name: 'Amazon Redshift Serverless',
        namespace: 'redshift-serverless',
    },
    {
        name: 'AWS Migration Hub Refactor Spaces',
        namespace: 'refactor-spaces',
    },
    {
        name: 'Amazon Rekognition',
        namespace: 'rekognition',
    },
    {
        name: 'AWS rePost Private',
        namespace: 'repostspace',
    },
    {
        name: 'AWS Resilience Hub',
        namespace: 'resiliencehub',
    },
    {
        name: 'Tag Editor',
        namespace: 'resource-explorer',
    },
    {
        name: 'AWS Resource Explorer',
        namespace: 'resource-explorer-2',
    },
    {
        name: 'AWS Resource Groups',
        namespace: 'resource-groups',
    },
    {
        name: 'Amazon RHEL Knowledgebase Portal',
        namespace: 'rhelkb',
    },
    {
        name: 'AWS RoboMaker',
        namespace: 'robomaker',
    },
    {
        name: 'AWS Identity and Access Management Roles Anywhere',
        namespace: 'rolesanywhere',
    },
    {
        name: 'Amazon Route 53',
        namespace: 'route53',
    },
    {
        name: 'Amazon Route 53 Recovery Cluster',
        namespace: 'route53-recovery-cluster',
    },
    {
        name: 'Amazon Route 53 Recovery Controls',
        namespace: 'route53-recovery-control-config',
    },
    {
        name: 'Amazon Route 53 Recovery Readiness',
        namespace: 'route53-recovery-readiness',
    },
    {
        name: 'Amazon Route 53 Domains',
        namespace: 'route53domains',
    },
    {
        name: 'Amazon Route 53 Profiles',
        namespace: 'route53profiles',
    },
    {
        name: 'Amazon Route 53 Resolver',
        namespace: 'route53resolver',
    },
    {
        name: 'AWS CloudWatch RUM',
        namespace: 'rum',
    },
    {
        name: 'Amazon S3',
        namespace: 's3',
    },
    {
        name: 'Amazon S3 Object Lambda',
        namespace: 's3-object-lambda',
    },
    {
        name: 'Amazon S3 on Outposts',
        namespace: 's3-outposts',
    },
    {
        name: 'Amazon S3 Express',
        namespace: 's3express',
    },
    {
        name: 'Amazon S3 Tables',
        namespace: 's3tables',
    },
    {
        name: 'Amazon SageMaker',
        namespace: 'sagemaker',
    },
    {
        name: 'Amazon SageMaker data science assistant',
        namespace: 'sagemaker-data-science-assistant',
    },
    {
        name: 'Amazon SageMaker geospatial capabilities',
        namespace: 'sagemaker-geospatial',
    },
    {
        name: 'Amazon SageMaker Ground Truth Synthetic',
        namespace: 'sagemaker-groundtruth-synthetic',
    },
    {
        name: 'Amazon SageMaker with MLflow',
        namespace: 'sagemaker-mlflow',
    },
    {
        name: 'AWS Savings Plans',
        namespace: 'savingsplans',
    },
    {
        name: 'Amazon EventBridge Scheduler',
        namespace: 'scheduler',
    },
    {
        name: 'Amazon EventBridge Schemas',
        namespace: 'schemas',
    },
    {
        name: 'AWS Supply Chain',
        namespace: 'scn',
    },
    {
        name: 'Amazon SimpleDB',
        namespace: 'sdb',
    },
    {
        name: 'AWS Secrets Manager',
        namespace: 'secretsmanager',
    },
    {
        name: 'AWS Security Incident Response',
        namespace: 'security-ir',
    },
    {
        name: 'AWS Security Hub',
        namespace: 'securityhub',
    },
    {
        name: 'Amazon Security Lake',
        namespace: 'securitylake',
    },
    {
        name: 'AWS Serverless Application Repository',
        namespace: 'serverlessrepo',
    },
    {
        name: 'AWS Service Catalog',
        namespace: 'servicecatalog',
    },
    {
        name: 'AWS Cloud Map',
        namespace: 'servicediscovery',
    },
    {
        name: 'AWS Microservice Extractor for .NET',
        namespace: 'serviceextract',
    },
    {
        name: 'Service Quotas',
        namespace: 'servicequotas',
    },
    {
        name: 'Amazon SES',
        namespace: 'ses',
    },
    {
        name: 'AWS Shield',
        namespace: 'shield',
    },
    {
        name: 'AWS Signer',
        namespace: 'signer',
    },
    {
        name: 'AWS Signin',
        namespace: 'signin',
    },
    {
        name: 'AWS SimSpace Weaver',
        namespace: 'simspaceweaver',
    },
    {
        name: 'AWS Server Migration Service',
        namespace: 'sms',
    },
    {
        name: 'Amazon Pinpoint SMS and Voice Service',
        namespace: 'sms-voice',
    },
    {
        name: 'AWS Snow Device Management',
        namespace: 'snow-device-management',
    },
    {
        name: 'AWS Snowball',
        namespace: 'snowball',
    },
    {
        name: 'Amazon SNS',
        namespace: 'sns',
    },
    {
        name: 'AWS End User Messaging Social',
        namespace: 'social-messaging',
    },
    {
        name: 'AWS SQL Workbench',
        namespace: 'sqlworkbench',
    },
    {
        name: 'Amazon SQS',
        namespace: 'sqs',
    },
    {
        name: 'AWS Systems Manager',
        namespace: 'ssm',
    },
    {
        name: 'AWS Systems Manager Incident Manager Contacts',
        namespace: 'ssm-contacts',
    },
    {
        name: 'AWS Systems Manager GUI Connect',
        namespace: 'ssm-guiconnect',
    },
    {
        name: 'AWS Systems Manager Incident Manager',
        namespace: 'ssm-incidents',
    },
    {
        name: 'AWS Systems Manager Quick Setup',
        namespace: 'ssm-quicksetup',
    },
    {
        name: 'AWS Systems Manager for SAP',
        namespace: 'ssm-sap',
    },
    {
        name: 'Amazon Message Gateway Service',
        namespace: 'ssmmessages',
    },
    {
        name: 'AWS IAM Identity Center (successor to AWS Single Sign-On)',
        namespace: 'sso',
    },
    {
        name: 'AWS IAM Identity Center (successor to AWS Single Sign-On) directory',
        namespace: 'sso-directory',
    },
    {
        name: 'AWS IAM Identity Center OIDC service',
        namespace: 'sso-oauth',
    },
    {
        name: 'AWS Step Functions',
        namespace: 'states',
    },
    {
        name: 'AWS Storage Gateway',
        namespace: 'storagegateway',
    },
    {
        name: 'AWS Security Token Service',
        namespace: 'sts',
    },
    {
        name: 'AWS Support',
        namespace: 'support',
    },
    {
        name: 'AWS Support App in Slack',
        namespace: 'supportapp',
    },
    {
        name: 'AWS Support Plans',
        namespace: 'supportplans',
    },
    {
        name: 'AWS Support Recommendations',
        namespace: 'supportrecommendations',
    },
    {
        name: 'AWS Sustainability',
        namespace: 'sustainability',
    },
    {
        name: 'Amazon Simple Workflow Service',
        namespace: 'swf',
    },
    {
        name: 'Amazon CloudWatch Synthetics',
        namespace: 'synthetics',
    },
    {
        name: 'Amazon Resource Group Tagging API',
        namespace: 'tag',
    },
    {
        name: 'AWS Tax Settings',
        namespace: 'tax',
    },
    {
        name: 'Amazon Textract',
        namespace: 'textract',
    },
    {
        name: 'Amazon WorkSpaces Thin Client',
        namespace: 'thinclient',
    },
    {
        name: 'Amazon Timestream',
        namespace: 'timestream',
    },
    {
        name: 'Amazon Timestream InfluxDB',
        namespace: 'timestream-influxdb',
    },
    {
        name: 'AWS Tiros',
        namespace: 'tiros',
    },
    {
        name: 'AWS Telco Network Builder',
        namespace: 'tnb',
    },
    {
        name: 'Amazon Transcribe',
        namespace: 'transcribe',
    },
    {
        name: 'AWS Transfer Family',
        namespace: 'transfer',
    },
    {
        name: 'Amazon Translate',
        namespace: 'translate',
    },
    {
        name: 'AWS Trusted Advisor',
        namespace: 'trustedadvisor',
    },
    {
        name: 'AWS Diagnostic tools',
        namespace: 'ts',
    },
    {
        name: 'AWS User Subscriptions',
        namespace: 'user-subscriptions',
    },
    {
        name: 'AWS Marketplace Vendor Insights',
        namespace: 'vendor-insights',
    },
    {
        name: 'AWS Verified Access',
        namespace: 'verified-access',
    },
    {
        name: 'Amazon Verified Permissions',
        namespace: 'verifiedpermissions',
    },
    {
        name: 'Amazon Connect Voice ID',
        namespace: 'voiceid',
    },
    {
        name: 'Amazon VPC Lattice',
        namespace: 'vpc-lattice',
    },
    {
        name: 'Amazon VPC Lattice Services',
        namespace: 'vpc-lattice-svcs',
    },
    {
        name: 'AWS PrivateLink',
        namespace: 'vpce',
    },
    {
        name: 'AWS WAF',
        namespace: 'waf',
    },
    {
        name: 'AWS WAF Regional',
        namespace: 'waf-regional',
    },
    {
        name: 'AWS WAF V2',
        namespace: 'wafv2',
    },
    {
        name: 'Amazon WorkSpaces Application Manager',
        namespace: 'wam',
    },
    {
        name: 'AWS Well-Architected Tool',
        namespace: 'wellarchitected',
    },
    {
        name: 'AWS Wickr',
        namespace: 'wickr',
    },
    {
        name: 'Amazon Q in Connect',
        namespace: 'wisdom',
    },
    {
        name: 'Amazon WorkDocs',
        namespace: 'workdocs',
    },
    {
        name: 'Amazon WorkLink',
        namespace: 'worklink',
    },
    {
        name: 'Amazon WorkMail',
        namespace: 'workmail',
    },
    {
        name: 'Amazon WorkMail Message Flow',
        namespace: 'workmailmessageflow',
    },
    {
        name: 'Amazon WorkSpaces',
        namespace: 'workspaces',
    },
    {
        name: 'Amazon WorkSpaces Secure Browser',
        namespace: 'workspaces-web',
    },
    {
        name: 'AWS X-Ray',
        namespace: 'xray',
    },
];
