name: Main
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy_dev:
    needs:
      - tests
    permissions:
      id-token: write
      contents: read
      actions: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::774305579662:role/cloud-snitch-github-actio-GithubActionsRoleF5CC769F-MoeCHSu77MYt
          aws-region: us-east-1
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: dev
      - name: NPM Install
        working-directory: aws
        run: npm ci
      - name: Deploy
        working-directory: aws
        run: |
          npx aws-cdk deploy '*-dev' --require-approval never
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          environment_url: https://cloud-snitch.ccbrown.dev
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
